In [1]:
%pip install numpy



[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
np.ones([2,2],dtype=np.int64)

array([[1, 1],
       [1, 1]])

In [5]:
np.zeros([2,2],dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [11]:
new_array=np.zeros([2,3],dtype=np.int64)

In [12]:
new_array.shape

(2, 3)

In [13]:
new_array.fill(0)

In [14]:
new_array

array([[0, 0, 0],
       [0, 0, 0]])